version: "3.9"

services:
  backend:
    environment:
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_TRACE_URL: http://host.docker.internal:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8546/
      CHAIN_ID: "71602"
      COIN_NAME: AEX
      COIN: AEX
      MICROSERVICE_SC_VERIFIER_ENABLED: "false"
      MICROSERVICE_VISUALIZE_SOL2UML_ENABLED: "false"
      MICROSERVICE_SIG_PROVIDER_ENABLED: "false"
      MICROSERVICE_ACCOUNT_ABSTRACTION_ENABLED: "false"
      NFT_MEDIA_HANDLER_ENABLED: "false"

  frontend:
    environment:
      NEXT_PUBLIC_NETWORK_NAME: AESC Devnet
      NEXT_PUBLIC_NETWORK_SHORT_NAME: AESC
      NEXT_PUBLIC_NETWORK_ID: "71602"
      NEXT_PUBLIC_NETWORK_CURRENCY_NAME: AEX
      NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: AEX
      NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18"
      NEXT_PUBLIC_STATS_API_HOST: ""
      NEXT_PUBLIC_VISUALIZE_API_HOST: ""
